### ISSUE TITLE
raise error when use GPAW potential

### ISSUE THREAD

**Issue by JizheCui** [jacobjma/abTEM#20]
Hello Jacob,
When I use the DFT potential in abTEM， there is always error, even when just copy the code of walkthroughs jupyter file '10_DFT.ipynb' and paste them into a new python file

here is the code:
'''
import numpy as np
import matplotlib.pyplot as plt
from gpaw import GPAW
from abtem.dft import GPAWPotential
from ase.io import read
from abtem import *

atoms = read('./hexagonal_graphene.cif')

gpaw = GPAW(h=.1, txt=None, kpts=(3,3,1))
atoms.calc = gpaw
print(atoms.get_potential_energy())

# gpaw.write('./8_graphene.gpw')
dft_pot = GPAWPotential(gpaw, sampling=.02)
dft_array = dft_pot.build()
'''

here is the error:
'''
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/pycharm-2020.2.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-2020.2.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/d/CODE/PYTHON_CODE/mycode/test_all/abtem_test/8_gpaw_test.py", line 16, in <module>
    dft_array = dft_pot.build()
  File "/mnt/d/CODE/PYTHON_CODE/abTEM-master/abTEM-master/abtem/potentials.py", line 230, in build
    for start, end, potential_slice in generator:
  File "/mnt/d/CODE/PYTHON_CODE/abTEM-master/abTEM-master/abtem/dft.py", line 261, in generate_slices
    sampling)
TypeError: not enough arguments: expected 8, got 7
'''

After cheching the code, the 'interpolate_radial_functions' was called but only transfer 7 arguments, ‘rle_encoding: np.ndarray’ was missed.
What is the ‘rle_encoding: np.ndarray’? And how to fixed this? Is there anything wrong with my usage?

Looking forward to your reply soon!

**Comment by JizheCui** [comment]
current version: 1.0.0beta15

**Comment by JizheCui** [comment]
It works now, maybe because I put abtem source code to my project directory, when it was deleted, It works.
Thanks a lot!
