### ISSUE TITLE
ValueError in abtem.potentials.soft_function()

### ISSUE THREAD

**Issue by drpaulsharp** [jacobjma/abTEM#57]
When running a STEM scan using abtem 1.0.0b24 and numpy 1.21.2, the following error occurs:

Earlier versions of numpy fail due to the use of the "sliding_window_view" routine.

  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 798, in get_integrator
    return self._integrators[number]
KeyError: 8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "images.py", line 113, in <module>
    measurement = probe.scan(scan, haadf_detector, potential, pbar=True)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/waves.py", line 1953, in scan
    for indices, exit_probes in probe_generator:
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/waves.py", line 1848, in _generate_probes
    for potential_config in potential.generate_frozen_phonon_potentials(pbar=potential_pbar):
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 990, in generate_frozen_phonon_potentials
    yield self.build(pbar=pbar)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 262, in build
    for start, end, potential_slice in generator:
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 904, in _generate_slices_finite
    max_cutoff = max(self.get_integrator(number).cutoff for number in unique)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 904, in <genexpr>
    max_cutoff = max(self.get_integrator(number).cutoff for number in unique)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 807, in get_integrator
    self._integrators[number] = PotentialIntegrator(soft_function, r, max_interval, cutoff)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 331, in __init__
    value, error_estimate, step_size, order = integrate(f, -1, 1, self._tolerance)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/tanh_sinh.py", line 145, in integrate
    left_summands = f_left(y0) * weights
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/tanh_sinh.py", line 112, in f_left
    return f(a + s)
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 329, in f
    return self._function(np.sqrt(self.r[0] ** 2 + (z * max_interval / 2 + max_interval / 2) ** 2))
  File "/home/vol02/scarf982/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 777, in soft_function
    result[valid] = self._function(r[valid], self.parameters[number])
TypeError: expected dtype object, got 'numpy.dtype[float64]'

**Comment by jacobjma** [comment]
Thank you for the report.

I reverted the commit introducing the `sliding_window_view` function, as we should not require the latest `NumPy`. However, the traceback you provided makes your issue look more like a `numba` issue.

**Comment by drpaulsharp** [comment]
Thanks Jacob, a fresh Anaconda environment seems to have resolved this issue.
