### ISSUE TITLE
Numba / Cuda issue 

### ISSUE THREAD

**Issue by alex-rakowski** [jacobjma/abTEM#9]
I ran `1_million_probe_positions.py`on a cluster successfully a couple of times on my local HPC (CentOS-7, V-100, Cuda 10.1), it worked a multiple times (I was running repeats to get an idea of perforamnce),  but then it stopped and produces the following error (below). It runs the potential and multislice, and fails on `measurement` part of a code. I can get it to run the script  using CPU only, and I can get `cbed_8_million_atoms` and `run_STEM_MoS2.py` to run using GPU, I've tried a couple of fresh differet conda envrionments (pasted below). I suspect that its an issue with the HPC, as I haven't been able to reproduce it locally, but while I wait on HPC support I thought I'd check if anyone has seen this  

```
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/core/typing/context.py", line 353, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/core/typing/typeof.py", line 35, in typeof
    raise ValueError(msg)
ValueError: Cannot determine Numba type of <class 'cupy.core.core.ndarray'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 237, in initialize
    self.cuInit(0)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [-1] Call to cuInit results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_script.py", line 47, in <module>
    measurements = S.scan(scan, [detector], potential, max_batch_expansion=35)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/abtem/waves.py", line 1544, in scan
    new_measurement = detector.detect(exit_probes)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/abtem/detect.py", line 424, in detect
    sum_run_length_encoded(intensity, result, separators)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/abtem/cuda_kernels.py", line 91, in launch_sum_run_length_encoded
    sum_run_length_encoded[blockspergrid, threadsperblock](array, result, separators)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/compiler.py", line 773, in __call__
    self.stream, self.sharedmem)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/compiler.py", line 877, in call
    for a in args])
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/compiler.py", line 877, in <listcomp>
    for a in args])
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/core/typing/context.py", line 356, in resolve_argument_type
    return typeof(numba.cuda.as_cuda_array(val), Purpose.argument)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/api.py", line 61, in as_cuda_array
    owner=obj)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 223, in _require_cuda_context
    with _runtime.ensure_context():
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 121, in ensure_context
    with driver.get_active_context():
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 393, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 280, in __getattr__
    self.initialize()
  File "/data/homezvol2/arakowsk/.conda/envs/abtem/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 240, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 
[-1] Call to cuInit results in UNKNOWN_CUDA_ERROR:
```

```
_libgcc_mutex             0.1                        main  
abtem                     1.0.0b13                 pypi_0    pypi
ase                       3.20.1                   pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.12.8            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.12.5        py37h06a4308_0  
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cupy-cuda101              8.2.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
fastrlock                 0.5                      pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.35.0                   pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numba                     0.52.0                   pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
numpy-base                1.19.2           py37hfa32c7d_0  
openssl                   1.1.1i               h27cfd23_0  
pandas                    1.1.3            py37he6710b0_0  
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3.1           py37h06a4308_0  
psutil                    5.7.3                    pypi_0    pypi
pyfftw                    0.12.0                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                      py_0  
pytz                      2020.4             pyhd3eb1b0_0  
readline                  8.0                  h7b6447c_0  
scipy                     1.5.4                    pypi_0    pypi
setuptools                51.0.0           py37h06a4308_2  
six                       1.15.0           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.54.1                   pypi_0    pypi
wheel                     0.36.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by jacobjma** [comment]
Hmm, I can't be sure what this is. 

As a debugging step, you could try to change the detector from FlexibleAnnularDetector to just AnnularDetector.

**Comment by alex-rakowski** [comment]
It runs when I replace FlexibleAnnularDetector with one or more AnnularDetectors.

**Comment by jacobjma** [comment]
It must be triggered by the `sum_run_length_encoded` function then. Does other Numba functions permit cupy arrays as an argument?

Try for example:
```python
import math
import cupy as cp
from numba import cuda

@cuda.jit
def just_a_cosine(arr):
    x = cuda.grid(1)
    if x < arr.size:
        arr[x] = math.cos(arr[x])

arr = cp.random.random((10,), dtype=cp.float32)
just_a_cosine[(1,), (10,)](arr)
```

**Comment by alex-rakowski** [comment]
That raises the same error as above on HPC, but runs fine on my local
machine.

I'm still trouble shooting with hpc support, this will definitely help
simplify. Hopefully it is just something with my cuda environment.

**Comment by jacobjma** [comment]
This seems to be a Numba issue, so I will close this now.
